### PR TITLE
fix: partially freezes internal functions (#33)

### PR DESCRIPTION
**Pull request by zsimo**
hello, hope it solves the issue

### CODE REVIEW

**Comment by Cadienvan** [comment]
Hi @zsimo thank you for your contribution.
I like your approach, yet our issue still remains.

It seems the exported internal functions are frozen and can't be changed at all.
I did some research about it and it seems related to how the language behaves, so not sure what approach to go for.

If you try to create a plugin which overrides the internal `getDataCacheKey` function in the Hooks.SETUP hook and then try to call it again in another hook, this will come back to its original signature because, in fact, it isn't saved at all.

I'll keep the PR open as it is an interesting approach, yet not useful per our current situation.

What do you think? Any ideas?

**Comment by zsimo** [comment]
HI @Cadienvan, can you please provide an example of the plugin usage you are referring to? Not sure to get it. Thanks

**Comment by Cadienvan** [comment]
https://gist.github.com/Cadienvan/fda1dc6eb032b0fdbc99806301dbacdd
Schermata 2023-04-03 alle 17 14 25

As you can see, it doesn't reflect the updates.
I'd expect 'abc' to be returned.

**Comment by zsimo** [comment]
It seems to work if you overwrite the internal function inside the "INIT" hook instead of the "SETUP" one. Is there any difference in how the hooks behave?
This code works:
``` js

    const myPlugin = {
      name: 'myPlugin',
      hooks: [
        {
          hook: Hooks.INIT,
          action: async (payload) => {
            payload.internals.getDataCacheKey = function () {
              console.log("should be possible");
              return "ciao";
            };
          }
        },
        {
          hook: Hooks.EXECUTION_PRE,
          action: async (payload) => {
            console.log(payload.internals.getDataCacheKey()); // ciao
          }
        }
      ]
    };

```

**Comment by Cadienvan** [comment]
You are right.
We should specify it better in the docs as it got me because I forgot about it ahah

I will merge your PR after checks are passed so I can start working on this difference.

Thanks a lot!

**Pull request merged**
